[tool.black]
line-length = 120

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
disallow_untyped_calls = true
exclude = ["scripts", "docs", "test"]
disable_error_code = [
    "call_overload"
    ]

[tool.coverage.report]
exclude_also = [
    'def __repr__',
    'if self.debug:',
    'if settings.DEBUG',
    'raise AssertionError',
    'raise NotImplementedError',
    'if 0:',
    'if __name__ == .__main__.:',
    'if TYPE_CHECKING:',
    'class .*\bProtocol\):',
    '@(abc\.)?abstractmethod',
]